# Generated by Django 3.2.4 on 2022-05-11 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Due_date', models.DateField()),
                ('Title', models.CharField(max_length=120)),
                ('Description', models.CharField(max_length=500)),
                ('Priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('Repeat_Days', models.IntegerField()),
                ('Completed', models.BooleanField(default=False)),
                ('Folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.folder')),
                ('Responsible_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
