# Generated by Django 3.2.4 on 2022-05-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='Name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
