# Generated by Django 3.2.4 on 2022-05-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Repeat_Days',
            field=models.PositiveIntegerField(),
        ),
    ]
